package sanandreasp.mods.TurretMod3.registry;

import sanandreasp.mods.managers.SAP_LanguageManager;

public class DefLangs {
	public static void setupLang(SAP_LanguageManager lmInst) {
		lmInst.addLangPropS("turretmod3.turret.namet1a", 	"Crossbow Turret (T1)");
		lmInst.addLangPropS("turretmod3.turret.desct1a", 	"Turret which shoots arrows. It's relatively cheap, so it's ideal as your basic defense.");
		lmInst.addLangPropS("turretmod3.turret.amtp0t1a",	"Arrows");
		lmInst.addLangPropS("turretmod3.turret.namet1s", 	"Shotgun Turret (T1)");
		lmInst.addLangPropS("turretmod3.turret.desct1s",	"Turret which shoots pebbles. It has the same stats as the T1 turret, but makes the lowest damage. Ideal for hitting multiple targets at once.");
		lmInst.addLangPropS("turretmod3.turret.amtp0t1s", 	"Pebbles");
		lmInst.addLangPropS("turretmod3.turret.namet2m", 	"Minigun Turret (T2)");
		lmInst.addLangPropS("turretmod3.turret.desct2m",	"Turret which shoots seeds. It has double the health as the T1 turrets, the fastest cooldown time but makes low damage. Ideal for crowd control in combination with the T1 Shotgun Turret.");
		lmInst.addLangPropS("turretmod3.turret.amtp0t2m", 	"Wheat seeds");
		lmInst.addLangPropS("turretmod3.turret.amtp1t2m", 	"Melon seeds");
		lmInst.addLangPropS("turretmod3.turret.amtp2t2m", 	"Pumpkin seeds");
		lmInst.addLangPropS("turretmod3.turret.namet2r", 	"Revolver Turret (T2)");
		lmInst.addLangPropS("turretmod3.turret.desct2r",	"This turret has double the health and damage, +8 blocks more range, shoots twice as fast and is more expensive than the Crossbow Turret. Ideal for intermediate defense systems.");
		lmInst.addLangPropS("turretmod3.turret.amtp0t2r", 	"Bullets");
		lmInst.addLangPropS("turretmod3.turret.namet3l", 	"Laser Turret (T3)");
		lmInst.addLangPropS("turretmod3.turret.desct3l",	"This turret can be considered as the upgraded version of the Revolver turret. It shoots lasers which deal 6 HP of damage, it has 60 HP of health and 1.5 times more range! Choose one of these turrets for your advanced defense system.");
		lmInst.addLangPropS("turretmod3.turret.amtp0t3l", 	"Red Laser (Redstone)");
		lmInst.addLangPropS("turretmod3.turret.amtp1t3l", 	"Blue Laser (Lapis Lazuli)");
		lmInst.addLangPropS("turretmod3.turret.namet3f", 	"Flamethrower Turret (T3)");
		lmInst.addLangPropS("turretmod3.turret.desct3f",	"This turret is ideal to burn your enemies into ashes! It is naturally immune to fire itself and has the same stats as the Laser Turret, except it does half the damage and technically shoots rapidly.");
		lmInst.addLangPropS("turretmod3.turret.amtp0t3f", 	"Fire");
		lmInst.addLangPropS("turretmod3.turret.namet4s", 	"Sniper Turret (T4)");
		lmInst.addLangPropS("turretmod3.turret.desct4s",	"This turret is there if you want snipe enemies in your area or just make sure there are no enemies! It has a really high range, although it has less health than the T3 Laser turret and a really high cooldown time!");
		lmInst.addLangPropS("turretmod3.turret.amtp0t4s", 	"Plasma");
		lmInst.addLangPropS("turretmod3.turret.namet4f", 	"FLAK Turret (T4)");
		lmInst.addLangPropS("turretmod3.turret.desct4f",	"Use this turret if you want to shoot flying stuff like Ghasts. It has an enormous range of 50 blocks, horizontally as well as upwards. If you give it the fitting rocket, you can increase that range up to 100 blocks!");
		lmInst.addLangPropS("turretmod3.turret.amtp0t4f", 	"Ballistic Rocket TB50");
		lmInst.addLangPropS("turretmod3.turret.amtp1t4f", 	"Ballistic Rocket TB75");
		lmInst.addLangPropS("turretmod3.turret.amtp2t4f", 	"Ballistic Rocket TB100");
		lmInst.addLangPropS("turretmod3.turret.amtp3t4f", 	"Guided Rocket TG50");
		lmInst.addLangPropS("turretmod3.turret.amtp4t4f", 	"Guided Rocket TG75");
		lmInst.addLangPropS("turretmod3.turret.amtp5t4f", 	"Guided Rocket TG100");
		lmInst.addLangPropS("turretmod3.turret.namet5r", 	"Railgun Turret (T5)");
		lmInst.addLangPropS("turretmod3.turret.desct5r",	"This is one of the most powerful turrets you've ever seen! And because of that, it's rather expensive. It's projectiles can go through targets without losing it's velocity, hitting max. 9 Entities behind the first one!");
		lmInst.addLangPropS("turretmod3.turret.amtp0t5r", 	"Ender Shards");
		lmInst.addLangPropS("turretmod3.turret.namet5a", 	"Artillery Turret (T5)");
		lmInst.addLangPropS("turretmod3.turret.desct5a",	"You want some high-ranged AOE? Then use this turret! It is the most expensive turret but really powerful! It can fire different types of Artillery shells, so be aware what you're using!");
		lmInst.addLangPropS("turretmod3.turret.nametss", 	"Snowball Turret (TS)");
		lmInst.addLangPropS("turretmod3.turret.desctss",	"This supporter turret can slowdown enemies, although without dealing any damage. Give the other turrets the time needed to kill their targets with this turret!");
		lmInst.addLangPropS("turretmod3.turret.amtp0tss", 	"Snowballs");
		lmInst.addLangPropS("turretmod3.turret.nametsc", 	"Collector Turret (TS)");
		lmInst.addLangPropS("turretmod3.turret.desctsc",	"You are bored from collecting XP orbs together after a fight or just don't miss one? Or do you want to store your collected XP somewhere? This turret can collect nearby XP orbs and can store them.");
		lmInst.addLangPropS("turretmod3.turret.nametsf", 	"Forcefield Turret (TS)"); //TODO: add description
		lmInst.addLangPropS("turretmod3.turret.desctsf",	"You ever wanted to protect you from incoming projectiles? You want to walk safely through the Nether without need for glass tunnels? Or just want to protect those villagers from those damn Zombies? The Forcefield Turret generates a protecting shield around it!");
		lmInst.addLangPropS("turretmod3.turret.nametsh", 	"Healing Turret (TS)");
		lmInst.addLangPropS("turretmod3.turret.desctsh",	"This is the medic under the turrets. It will heal nearby turrets if they get damaged. It is ideal if you don't want to waste a hell lot of healing items for your turrets! Also it is more resistant for explosions than a chest.");
		lmInst.addLangPropS("turretmod3.turret.amtp0tsh", 	"Health Beam (Glistering Melon)");
		lmInst.addLangPropS("turretmod3.turret.amtp1tsh", 	"Health Beam (Golden Carrots)");
		lmInst.addLangPropS("turretmod3.turret.amtp2tsh", 	"Health Beam (Gold Nugget)");
		
		lmInst.addLangPropS("turretmod3.upgrades.nameChest",			"Chest Grabber");
		lmInst.addLangPropS("turretmod3.upgrades.descChest", 			"Let your turret grab the content from chests with this upgrade! Put chests to the sides or below the turret, so that it can reach them.");
		lmInst.addLangPropS("turretmod3.upgrades.nameControl", 			"Control Seat");
		lmInst.addLangPropS("turretmod3.upgrades.descControl", 			"Ride your turret with this upgrade! Either right-click and choose \"Ride Turret\" in the Settings GUI or shift-right-click the turret to ride it. To get off, just right-click again with the TCU or nothing in your hands. To shoot press the Turret Shoot Key (F)");
		lmInst.addLangPropS("turretmod3.upgrades.nameExp", 				"XP Collector");
		lmInst.addLangPropS("turretmod3.upgrades.descExp", 				"Let your turrets collect and store XP from killed targets! All you have to do when the turret cannot store any more XP is to choose \"Get Experience\" in the TCU Settings GUI.");
		lmInst.addLangPropS("turretmod3.upgrades.nameInfbow", 			"Infinite Ammo");
		lmInst.addLangPropS("turretmod3.upgrades.descInfbow", 			"Don't want to let turrets waste ammo? Then this upgrade is the right! The turret won't consume ammo, but keep in mind, that you still need one projectile in the Turret!");
		lmInst.addLangPropS("turretmod3.upgrades.nameMoreXP", 			"More EXP Storage");
		lmInst.addLangPropS("turretmod3.upgrades.descMoreXP", 			"Wanna have more XP storage for your turret? Upgrade your turret with this and it will store 8 times more XP than before!");
		lmInst.addLangPropS("turretmod3.upgrades.nameFireImmune", 		"Fire Immunity");
		lmInst.addLangPropS("turretmod3.upgrades.descFireImmune", 		"Don't let your turret burnt down! Use this upgrade if you want to make sure no fiery creature can set it on fire or no lava can destroy it!");
		lmInst.addLangPropS("turretmod3.upgrades.nameGold", 			"Piercing");
		lmInst.addLangPropS("turretmod3.upgrades.descGold", 			"With this upgrade, projectiles can fly through enemies, hitting other behind it. Use this for the most efficiency.");
		lmInst.addLangPropS("turretmod3.upgrades.nameEconomy", 			"Economy");
		lmInst.addLangPropS("turretmod3.upgrades.descEconomy", 			"Do you want to waste less ammunition? The Economy upgrade will duplicate each bullet before it gets shoot out. Means the need of ammo will be cut in half!");
		lmInst.addLangPropS("turretmod3.upgrades.namePurify", 			"Purifying Flames");
		lmInst.addLangPropS("turretmod3.upgrades.descPurify", 			"This upgrade increases the efficiency of the Flamethrower by purifying the flames it shoots. Flames will do slightly more damage, pierce through enemies, set them longer on fire and will glow in a nice blue.");
		lmInst.addLangPropS("turretmod3.upgrades.nameEnderHit", 		"Ender-Hurting");
		lmInst.addLangPropS("turretmod3.upgrades.descEnderHit", 		"This upgrade will allow turrets to damage Enderman due to their weakness: Water. The projectiles will get a liquid core which is poisonous to them!");
		lmInst.addLangPropS("turretmod3.upgrades.namePrec", 			"Precision");
		lmInst.addLangPropS("turretmod3.upgrades.descPrec", 			"Once upgraded with this, every projectile will hit the target with 99.9% accuracy!");
		lmInst.addLangPropS("turretmod3.upgrades.nameSlowII", 			"Slowdown II");
		lmInst.addLangPropS("turretmod3.upgrades.descSlowII", 			"Slowdown your targets even more with this upgrade!");
		lmInst.addLangPropS("turretmod3.upgrades.nameStopMove", 		"Movement Blocking");
		lmInst.addLangPropS("turretmod3.upgrades.descStopMove", 		"entirely blocks the movement of a target! Don't let your turrets get endangered by incoming, revengeful enemies!");
		lmInst.addLangPropS("turretmod3.upgrades.nameTCollect", 		"Turret-XP Collecting");
		lmInst.addLangPropS("turretmod3.upgrades.descTCollect", 		"You want to get the XP from your turrets and store it in the Collector? Then upgrade it with this! The Collector turret is then able to extract the XP from nearby turrets.");
		lmInst.addLangPropS("turretmod3.upgrades.nameICollect", 		"Item Collecting");
		lmInst.addLangPropS("turretmod3.upgrades.descICollect", 		"You're afraid of losing your items upon death or just don't want tu run around to get your drops from fought mobs? With this upgrade the Collector turret can store items in adjacent chests! Put chests to the sides or below the turret, so that it can reach them.");
		lmInst.addLangPropS("turretmod3.upgrades.nameShieldRngI", 		"Range Increase I");
		lmInst.addLangPropS("turretmod3.upgrades.descShieldRngI", 		"You think the shield is too small? Then upgrade your Forcefield Turret with this to increase the shield's size up to 16 blocks.");
		lmInst.addLangPropS("turretmod3.upgrades.nameShieldRngII", 		"Range Increase II");
		lmInst.addLangPropS("turretmod3.upgrades.descShieldRngII", 		"You still think the shield not big enough? This upgrade will allow the Forcefield turret to generate a shield with a size of 32 blocks!");
		lmInst.addLangPropS("turretmod3.upgrades.nameShieldPtsIncr",	"Shield Strenghtener");
		lmInst.addLangPropS("turretmod3.upgrades.descShieldPtsIncr",	"This upgrade will increase the shield points from your Forcefield Turret up to 5000. A stronger shield for hordes of enemies!");
		lmInst.addLangPropS("turretmod3.upgrades.nameShieldRepIncr",	"Shield Healer");
		lmInst.addLangPropS("turretmod3.upgrades.descShieldRepIncr",	"A shield will be healed 5 times faster than regular whilst upgraded with this one!");
		lmInst.addLangPropS("turretmod3.upgrades.nameShieldPush",		"Density Increaser");
		lmInst.addLangPropS("turretmod3.upgrades.descShieldPush",		"If you don't want to let mobs get to your defense, use this upgrade! It increases the density of the shield, so that mobs (which are marked in the target list) will be pushed out of the Forcefield.");
		lmInst.addLangPropS("turretmod3.upgrades.nameRangeIncr",		"Range Extender");
		lmInst.addLangPropS("turretmod3.upgrades.descRangeIncr",		"Use the power of gold to increase the range of the Collector turret! Reach further distant items and XP, to be exact in a range of 64 blocks!");
		
		lmInst.addLangPropS("turretmod3.gui.tinfo.btndesc", 		"Description");
		lmInst.addLangPropS("turretmod3.gui.tinfo.btnbval", 		"Basic Values");
		lmInst.addLangPropS("turretmod3.gui.tinfo.btnahit", 		"Ammo and Health Items");
		lmInst.addLangPropS("turretmod3.gui.tinfo.btnupgd", 		"Upgrades");
		lmInst.addLangPropS("turretmod3.gui.tinfo.titpg1", 			"Turret Info - Description");
		lmInst.addLangPropS("turretmod3.gui.tinfo.titpg2", 			"Turret Info - Values");
		lmInst.addLangPropS("turretmod3.gui.tinfo.titpg3", 			"Turret Info - Items");
		lmInst.addLangPropS("turretmod3.gui.tinfo.titpg4", 			"Turret Info - Upgrades");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameMaxAmmo", 	"max. ammo capacity");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descMaxAmmo", 	"The maximal capacity of ammunition this turret can hold.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameMaxHealth", 	"max. health points");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descMaxHealth", 	"The maximal health points this turret can have.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameUpperRangeY", "upper Y-Range");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descUpperRangeY", "The upper Y-Range defines the range the turret can look for enemies above its head.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameLowerRangeY", "lower Y-Range");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descLowerRangeY", "The lower Y-Range defines the range the turret can look for enemies below its base.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameRangeX", 		"X-Range");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descRangeX",		"The X-Range defines the range the turret can look for enemies horizontally.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameDamage", 		"Damage");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descDamage", 		"The damage the turret deals to an entity each projectile.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.nameExp", 		"max. Experience capacity");
		lmInst.addLangPropS("turretmod3.gui.tinfo.descExp", 		"The max. capacity of Experience the turret can hold after upgraded with the XP upgrade.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.hoverPG2", 		"hover over an icon above to see the information.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.hoverPG4", 		"hover over an entry to see the information.");
		lmInst.addLangPropS("turretmod3.gui.tinfo.blocks",			"blocks");
		lmInst.addLangPropS("turretmod3.gui.tinfo.ammoitems", 		"Ammo Items");
		lmInst.addLangPropS("turretmod3.gui.tinfo.healitems", 		"Healing Items");
		lmInst.addLangPropS("turretmod3.gui.tinfo.projectiles", 	"porjectile|projectiles");
		lmInst.addLangPropS("turretmod3.gui.tinfo.healthpts", 		"health point|health points");
		lmInst.addLangPropS("turretmod3.gui.tinfo.upgToolTip", 		"Name|Item|Requires");
		
		lmInst.addLangPropS("turretmod3.gui.tcu.titTargets",		"TCU - Targets");
		lmInst.addLangPropS("turretmod3.gui.tcu.tgtMonster", 		"Monsters");
		lmInst.addLangPropS("turretmod3.gui.tcu.tgtAnimals", 		"Animals");
		lmInst.addLangPropS("turretmod3.gui.tcu.tgtOthers", 		"Other Entities");
		lmInst.addLangPropS("turretmod3.gui.tcu.btninfo", 			"Information");
		lmInst.addLangPropS("turretmod3.gui.tcu.btntarg", 			"Targets");
		lmInst.addLangPropS("turretmod3.gui.tcu.btnsetg", 			"Settings");
		lmInst.addLangPropS("turretmod3.gui.tcu.titInfo", 			"TCU - Informations");
		lmInst.addLangPropS("turretmod3.gui.tcu.infoHealth", 		"Health");
		lmInst.addLangPropS("turretmod3.gui.tcu.infoAmmo", 			"Ammunition");
		lmInst.addLangPropS("turretmod3.gui.tcu.infoShield",		"Shield Points");
		lmInst.addLangPropS("turretmod3.gui.tcu.infoType", 			"Type");
		lmInst.addLangPropS("turretmod3.gui.tcu.infoExp", 			"Experience Points");
		lmInst.addLangPropS("turretmod3.gui.tcu.infoExpNo", 		"upgrade not available");
		lmInst.addLangPropS("turretmod3.gui.tcu.misc", 				"Miscellaneous");
		lmInst.addLangPropS("turretmod3.gui.tcu.miscUP", 			"Turret name|Owner|Target|Scanning for targets|Has Mobile Base");
		lmInst.addLangPropS("turretmod3.gui.tcu.yesNo", 			"Yes|No");
		lmInst.addLangPropS("turretmod3.gui.tcu.titUpgrades", 		"TCU - Upgrades");
		lmInst.addLangPropS("turretmod3.gui.tcu.titSettings", 		"TCU - Settings");
		lmInst.addLangPropS("turretmod3.gui.tcu.stgDismantle", 		"Dismantle Turret");
		lmInst.addLangPropS("turretmod3.gui.tcu.stgUniqueTarget", 	"Target unique targets|on|off");
		lmInst.addLangPropS("turretmod3.gui.tcu.stgGetExp", 		"Get experience");
		lmInst.addLangPropS("turretmod3.gui.tcu.stgDismountBase", 	"Dismount from mobile base");
		lmInst.addLangPropS("turretmod3.gui.tcu.rideTurret", 		"Ride Turret");
		lmInst.addLangPropS("turretmod3.gui.tcu.frequency", 		"Frequency");
		lmInst.addLangPropS("turretmod3.gui.tcu.turretOnOff", 		"Activate Turret|Deactivate Turret");
		
		lmInst.addLangPropS("turretmod3.gui.laptop.titGeneral",		"Turret-Laptop - General");
		lmInst.addLangPropS("turretmod3.gui.laptop.titTargets",		"Turret-Laptop - Targets");
		lmInst.addLangPropS("turretmod3.gui.laptop.titUpgrades",	"Turret-Laptop - Upgrades");
		lmInst.addLangPropS("turretmod3.gui.laptop.titMisc",		"Turret-Laptop - Miscellaneous");
		lmInst.addLangPropS("turretmod3.gui.laptop.upgItems",		"Upgrade-Items");
		lmInst.addLangPropS("turretmod3.gui.laptop.btnprog",		"Program Turrets");
		lmInst.addLangPropS("turretmod3.gui.laptop.btngenrl",		"General Settings");
		lmInst.addLangPropS("turretmod3.gui.laptop.enableLabel",	"Status Label|Enable|Disable");
		lmInst.addLangPropS("turretmod3.gui.laptop.chngCrosshair",	"Change TurretCam Crosshair");
		lmInst.addLangPropS("turretmod3.gui.laptop.onTurret",		"Enable Turrets");
		lmInst.addLangPropS("turretmod3.gui.laptop.offTurret",		"Disable Turrets");
		lmInst.addLangPropS("turretmod3.gui.laptop.rstTargets",		"Reset Targeted Entities");
		lmInst.addLangPropS("turretmod3.gui.laptop.customName",		"Custom Name");
		lmInst.addLangPropS("turretmod3.gui.laptop.uniqueTgt",		"Enable Unique Targeting|Disable Unique Targeting");
		
		lmInst.addLangPropS("turretmod3.gui.invDismStorage",	"Dismantled Turret Storage");
		
		lmInst.addLangPropS("turretmod3.keys.turretShoot", 		"Turret Shoot Key");
		
		lmInst.addLangPropS("turretmod3.item.rocketRng", 		"Range");
		lmInst.addLangPropS("turretmod3.item.turretInfo", 		"name: %s|frequency: %s|new targets|new upgrades");
		lmInst.addLangPropS("turretmod3.item.artilleryInfo", 	"Explosion Radius|Spreads Fire|Dispersing Shrapnels|Ground-Griefing");
		
		lmInst.addLangPropS("turretmod3.mainMenu.name", 		"Turret Mod Menu");
	}
}
